from enum import Enum
from tg_bot_float_telegram_app.tg_constants import (
    MY_SUBSCRIPTIONS_TEXT,
    SUBSCRIBE_TEXT,
    UNSUBSCRIBE_TEXT,
    BUY_TEXT,
    CONFIRM_TEXT,
    CANCEL_TEXT,
    STATTRAK_VERSION_TEXT,
    DEFAULT_VERSION_TEXT,
)


class Buttons(Enum):
    SUB = SUBSCRIBE_TEXT
    UNSUB = UNSUBSCRIBE_TEXT
    MY_SUB = MY_SUBSCRIPTIONS_TEXT
    BUY = BUY_TEXT
    CONFIRM = CONFIRM_TEXT
    CANCEL = CANCEL_TEXT
    BASE_VERSION = DEFAULT_VERSION_TEXT
    STATTRAK_VERSION = STATTRAK_VERSION_TEXT
